# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-08 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoraFeed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('question', models.TextField()),
                ('code', markdownx.models.MarkdownxField()),
                ('publish', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Quora Feed',
                'verbose_name_plural': 'Quora Feed',
            },
        ),
    ]
