# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-08 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoraHandler', '0002_quorapage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quorapage',
            name='title',
            field=models.TextField(),
        ),
    ]
