# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(choices=[('Shivam', 'Shivam'), ('Saloni', 'Saloni')], max_length=20)),
                ('publish', models.BooleanField(default=True)),
                ('post', models.TextField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
