# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-06 22:35
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180706_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
