# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-06 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180706_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(choices=[('Shivam', 'Shivam Angurala'), ('Saloni', 'Saloni Angurala')], max_length=20),
        ),
    ]
