# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_displayimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='displayImage',
            field=models.ImageField(default='static/Images/image1.jpg', upload_to='media/%Y/%m/%d'),
        ),
    ]
