# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180707_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='displayImage',
            field=models.ImageField(default='/static/Images/image1.jpg', upload_to='static/media/%Y/%m/%d'),
        ),
    ]
