# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180708_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='useVideo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='videoEmbedding',
            field=markdownx.models.MarkdownxField(default=' '),
            preserve_default=False,
        ),
    ]
