# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-08 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('displayImage', models.ImageField(default='/static/Images/image1.jpg', upload_to='static/media/%Y/%m/%d')),
                ('imageHeight', models.IntegerField(default=200)),
                ('imageWidth', models.IntegerField(default=200)),
                ('intro', models.TextField()),
                ('name', models.TextField()),
                ('designation', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team',
            },
        ),
    ]
