# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-08 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
