# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('emailId', models.TextField()),
                ('name', models.TextField()),
                ('query', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('relevant', models.BooleanField(default=True)),
                ('sentiment', models.TextField(default='')),
                ('meta', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'User Queries',
                'verbose_name': 'User Query',
                'ordering': ['-created'],
            },
        ),
    ]
