# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUsPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='querydetail',
            name='reply',
            field=models.TextField(default=''),
        ),
    ]
