# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('body', markdownx.models.MarkdownxField()),
                ('backGroundImage', models.ImageField(default='/static/Images/image1.jpg', upload_to='static/media/%Y/%m/%d')),
                ('carousel1QuoteTitle', models.TextField()),
                ('carousel1Quote', models.TextField()),
                ('carousel1Image', models.ImageField(default='/static/Images/image1.jpg', upload_to='static/media/%Y/%m/%d')),
                ('carousel2QuoteTitle', models.TextField()),
                ('carousel2Quote', models.TextField()),
                ('carousel2Image', models.ImageField(default='/static/Images/image1.jpg', upload_to='static/media/%Y/%m/%d')),
                ('carousel3QuoteTitle', models.TextField()),
                ('carousel3Quote', models.TextField()),
                ('carousel3Image', models.ImageField(default='/static/Images/image1.jpg', upload_to='static/media/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
    ]
