# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-08 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bodyColor',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('brown', 'brown'), ('pink', 'pink'), ('orange', 'orange'), ('red', 'red'), ('gold', 'gold'), ('green', 'green'), ('chrome', 'chrome')], default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='carousel1QuoteColor',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('brown', 'brown'), ('pink', 'pink'), ('orange', 'orange'), ('red', 'red'), ('gold', 'gold'), ('green', 'green'), ('chrome', 'chrome')], default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='carousel1QuoteTitleColor',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('brown', 'brown'), ('pink', 'pink'), ('orange', 'orange'), ('red', 'red'), ('gold', 'gold'), ('green', 'green'), ('chrome', 'chrome')], default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='carousel2QuoteColor',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('brown', 'brown'), ('pink', 'pink'), ('orange', 'orange'), ('red', 'red'), ('gold', 'gold'), ('green', 'green'), ('chrome', 'chrome')], default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='carousel2QuoteTitleColor',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('brown', 'brown'), ('pink', 'pink'), ('orange', 'orange'), ('red', 'red'), ('gold', 'gold'), ('green', 'green'), ('chrome', 'chrome')], default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='carousel3QuoteColor',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('brown', 'brown'), ('pink', 'pink'), ('orange', 'orange'), ('red', 'red'), ('gold', 'gold'), ('green', 'green'), ('chrome', 'chrome')], default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='carousel3QuoteTitleColor',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('brown', 'brown'), ('pink', 'pink'), ('orange', 'orange'), ('red', 'red'), ('gold', 'gold'), ('green', 'green'), ('chrome', 'chrome')], default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='titleColor',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('brown', 'brown'), ('pink', 'pink'), ('orange', 'orange'), ('red', 'red'), ('gold', 'gold'), ('green', 'green'), ('chrome', 'chrome')], default='white', max_length=20),
        ),
    ]
